### ISSUE TITLE
Error on /pa modules upgrade

### ISSUE THREAD

**Issue by oskarkk** [Eredrim/pvparena#140]
I'm using pvparena 1.15.2 and Paper 1.18.2.

```
> pa modules upgrade
[03:45:10 WARN]: Unexpected exception while parsing console command "pa modules upgrade"
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.15.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[paper-1.18.2.jar:git-Paper-"f8e8d6c"]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:868) ~[paper-1.18.2.jar:git-Paper-"f8e8d6c"]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:510) ~[paper-1.18.2.jar:git-Paper-"f8e8d6c"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[paper-1.18.2.jar:git-Paper-"f8e8d6c"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-"f8e8d6c"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-"f8e8d6c"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-"f8e8d6c"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at com.google.gson.JsonArray.get(JsonArray.java:203) ~[gson-2.8.9.jar:?]
        at net.slipcor.pvparena.updater.AbstractUpdater.getFilenameFromJson(AbstractUpdater.java:92) ~[pvparena-1.15.2.jar:?]
        at net.slipcor.pvparena.updater.ModulesUpdater.downloadModulePack(ModulesUpdater.java:80) ~[pvparena-1.15.2.jar:?]
        at net.slipcor.pvparena.commands.PAA_Modules.commit(PAA_Modules.java:68) ~[pvparena-1.15.2.jar:?]
        at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:209) ~[pvparena-1.15.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

By the way, a command like `/pa modules sometext` will give no error message, a check for the 2nd arg should be added, but that's a different issue.

**Comment by Eredrim** [comment]
That's normal, I just forgot to upload the module release on github ^^. Fixed.

**Comment by oskarkk** [comment]
Maybe there should be some error message for a situation like that? Like "Cannot find the modules for this version".
