### ISSUE TITLE
[1.18.2][Paper] ChestFiller Module

### ISSUE THREAD

**Issue by X-Niter** [Eredrim/pvparena#144]
1.18.2 Paper with PVPArena.

Stack Trace of the error thrown in logs. I saw comments it's common for modules to not be functioning in 1.18.2. 
I'm putting this here so you can track this one.
```
 [PVP Arena] Task #178962 for pvparena v1.15.2 generated an exception
28.04 03:25:23 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
28.04 03:25:23 [Server] INFO at net.slipcor.pvparena.modules.blockrestore.RestoreContainer.parseStringToLocation(RestoreContainer.java:160) ~[?:?]
28.04 03:25:23 [Server] INFO at net.slipcor.pvparena.modules.blockrestore.RestoreContainer.saveChests(RestoreContainer.java:67) ~[?:?]
28.04 03:25:23 [Server] INFO at net.slipcor.pvparena.modules.blockrestore.Blocks.saveChests(Blocks.java:336) ~[?:?]
28.04 03:25:23 [Server] INFO at net.slipcor.pvparena.modules.blockrestore.Blocks.saveRegion(Blocks.java:372) ~[?:?]
28.04 03:25:23 [Server] INFO at net.slipcor.pvparena.modules.blockrestore.Blocks.parseStart(Blocks.java:355) ~[?:?]
28.04 03:25:23 [Server] INFO at net.slipcor.pvparena.classes.PACheck.handleStart(PACheck.java:807) ~[pvparena-1.15.2.jar:?]
28.04 03:25:23 [Server] INFO at net.slipcor.pvparena.arena.Arena.start(Arena.java:1859) ~[pvparena-1.15.2.jar:?]
28.04 03:25:23 [Server] INFO at net.slipcor.pvparena.arena.Arena.start(Arena.java:1813) ~[pvparena-1.15.2.jar:?]
28.04 03:25:23 [Server] INFO at net.slipcor.pvparena.runnables.StartRunnable.commit(StartRunnable.java:41) ~[pvparena-1.15.2.jar:?]
28.04 03:25:23 [Server] INFO at net.slipcor.pvparena.runnables.ArenaRunnable.run(ArenaRunnable.java:161) ~[pvparena-1.15.2.jar:?]
28.04 03:25:23 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-286]
28.04 03:25:23 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-286]
28.04 03:25:23 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-286]
28.04 03:25:23 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-286]
28.04 03:25:23 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-286]
28.04 03:25:23 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-286]
28.04 03:25:23 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-286]
28.04 03:25:23 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by Eredrim** [comment]
Solved on discord. There was as mistake in configuration of blockRestore which was resolved by typing `/pa <arena> !br clearinv`
