### ISSUE TITLE
NullPointerException LateLounge.hasSpawn

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#15]
Paper dev 138 (Spigot 1.14.4)
PVPArena dev 316

Player mis-typed CTF and this exception occurred.
```
[12:32:17] [Server thread/INFO]: player issued server command: /pa cft
[12:32:17] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.14.1-SNAPSHOT-b316
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.4.jar:git-Paper-138]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-138]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-138]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924) ~[patched_1.14.4.jar:git-Paper-138]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.modules.latelounge.LateLounge.hasSpawn(LateLounge.java:141) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:347) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.4.jar:git-Paper-138]
	... 17 more
```

**Comment by Eredrim** [comment]
I fixed it. Please try PvPArena_modules build #198.

**Comment by mibby** [comment]
Seems to be fixed after updating and reviewing my logs from the past few days. Thanks!
