### ISSUE TITLE
Squad Throwing Error

### ISSUE THREAD

**Issue by J-SHarper** [Eredrim/pvparena#29]
Having the Squads enhancement enabled in an arena throws this error on startup:

`[17:55:21] [Server thread/INFO]: [PVP Arena] Enabling pvparena v1.14.1-SNAPSHOT-b318
[17:55:21] [Server thread/INFO]: [PVP Arena] debugging: off
[17:55:21] [Server thread/WARN]: java.lang.NullPointerException
[17:55:21] [Server thread/WARN]: 	at net.slipcor.pvparena.modules.squads.Squads.configParse(Squads.java:50)
[17:55:21] [Server thread/WARN]: 	at net.slipcor.pvparena.loadables.ArenaModuleManager.configParse(ArenaModuleManager.java:123)
[17:55:21] [Server thread/WARN]: 	at net.slipcor.pvparena.managers.ConfigurationManager.configParse(ConfigurationManager.java:298)
[17:55:21] [Server thread/WARN]: 	at net.slipcor.pvparena.arena.Arena.<init>(Arena.java:115)
[17:55:21] [Server thread/WARN]: 	at net.slipcor.pvparena.managers.ArenaManager.load_arenas(ArenaManager.java:299)
[17:55:21] [Server thread/WARN]: 	at net.slipcor.pvparena.PVPArena.onEnable(PVPArena.java:501)
[17:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[17:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[17:55:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[17:55:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[17:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:487)
[17:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[17:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:890)
[17:55:21] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)`

The arena is then disabled.

**Comment by Eredrim** [comment]
It's actually a bug, a config key is missing. Waiting I fix int you can manually add the following property in your arena config file : `limits: []`. This have to be inserted in module -> squads part of your config.

**Comment by Eredrim** [comment]
Fixed in 1.15 snapshots. This mod has been partially rewritten to correct few other issues.
@J-SHarper Can you test it and confirm if all works ?
