### ISSUE TITLE
UnsupportedOperationException: null

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#34]
PVPArena compiled as of commit https://github.com/Eredrim/pvparena/commit/f8da5ec9ac987549217eb507c17d7ade5b467e2b
PVPArena Modules compiled as of https://github.com/Eredrim/pvparena_modules/commit/30e51880844bd90a74fd0dd6d13d075a921bb650
WorldEdit dev 4997 (bukkit-7.2.0-SNAPSHOT)
Tuinity dev 78 (Paper Fork - Spigot 1.15.2)

@Eredrim Broke in commit https://github.com/Eredrim/pvparena_modules/commit/8c6a61dc948db716f6fe2c6577feaf6f00b80ca2 ?
```
[10:43:18] [Server thread/WARN]: [PVP Arena] Task #313969 for pvparena v1.15.0-SNAPSHOT generated an exception
java.lang.UnsupportedOperationException: null
	at com.google.common.collect.UnmodifiableIterator.remove(UnmodifiableIterator.java:46) ~[patched_1.15.2.jar:git-Tuinity-"90d3772"]
	at com.sk89q.worldedit.extent.world.SideEffectExtent$1.resume(SideEffectExtent.java:113) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[?:?]
	at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:829) ~[?:?]
	at net.slipcor.pvparena.modules.worldedit.PAWE.load(PAWE.java:289) ~[?:?]
	at net.slipcor.pvparena.modules.worldedit.PAWE.load(PAWE.java:254) ~[?:?]
	at net.slipcor.pvparena.modules.worldedit.PAWE.reset(PAWE.java:344) ~[?:?]
	at net.slipcor.pvparena.loadables.ArenaModuleManager.reset(ArenaModuleManager.java:266) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.reset(Arena.java:1454) ~[?:?]
	at net.slipcor.pvparena.runnables.EndRunnable.commit(EndRunnable.java:53) ~[?:?]
	at net.slipcor.pvparena.runnables.ArenaRunnable.run(ArenaRunnable.java:161) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Tuinity-"90d3772"]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Tuinity-"90d3772"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1310) ~[patched_1.15.2.jar:git-Tuinity-"90d3772"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Tuinity-"90d3772"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1227) ~[patched_1.15.2.jar:git-Tuinity-"90d3772"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Tuinity-"90d3772"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Eredrim** [comment]
Please don't open issues for dev in progress. There is no dev build, no release and consequently no support for that version.

**Comment by mibby** [comment]
How would you like me to report issues from testing then?

**Comment by Eredrim** [comment]
I really appreciate your motivation but testing is not necessary for dev in progress. The code may change a lot and it will be under-performing to test it.

**Comment by mibby** [comment]
If you insist, I just thought I'd let you know of problems I come across. I've reported and helped debug hundreds of issues from slipcor's original fork to help test and the version prior to slipcor's takeover.

**Comment by Eredrim** [comment]
I understand and one again thank you for your work. However I use github to save my work and this work is incomplete the most of the time. Personally I consider there are three steps in development of this plugin : 
* Development itself: there are commits on a branch different of master. I develop, test fix and test plugin myself.
* Snapshots: code was tested a first time, it's like an alpha build, everyone can use and test it, but it's not necessarily stable.
* Release: code is stable and can be used on production servers.
