### ISSUE TITLE
IllegalArgumentException: Cannot set to an empty path

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#47]
PVPArena dev 328

Noticed this error in my logs. Should the exception be caught and outputting a nicer warning in-game?

```
[11:14:38] [Server thread/INFO]: player issued server command: /pa ctf8 flag
[11:14:40] [Server thread/INFO]: player issued server command: /pa ctf8 flags
[11:14:44] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to pvparena v1.15.0-SNAPSHOT-b328
java.lang.IllegalArgumentException: Cannot set to an empty path
	at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at org.bukkit.configuration.MemorySection.set(MemorySection.java:188) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at org.bukkit.configuration.MemorySection.set(MemorySection.java:222) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.slipcor.pvparena.core.Config.setManually(Config.java:850) ~[?:?]
	at net.slipcor.pvparena.managers.SpawnManager.setBlock(SpawnManager.java:769) ~[?:?]
	at net.slipcor.pvparena.goals.GoalFlags.commitSetFlag(GoalFlags.java:645) ~[?:?]
	at net.slipcor.pvparena.classes.PACheck.handleSetFlag(PACheck.java:688) ~[?:?]
	at net.slipcor.pvparena.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:491) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1067.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:438) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:164) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1505) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at xuan.cat.XuanCatAPI.code.b.c.a.g.a(Unknown Source) ~[?:?]
	at xuan.cat.XuanCatAPI.code.b.c.a.g.a(Unknown Source) ~[?:?]
	at xuan.cat.XuanCatAPI.code.b.c.a.g.a(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1161) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1154) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1130) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:973) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by Eredrim** [comment]
Fixed
