### ISSUE TITLE
InventoryRefillRunnable - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by TerraPrimal** [Eredrim/pvparena#5]
Greetings,
Just want to keep the items the player has when they die, tried using refillInventory: true and refillCustomInventory: true and even set preventDeath: false (just in case).

The items are "unique" however, nothing crazy. I have added a picture of the test item.

`
[10:26:07] [Server thread/WARN]: [PVP Arena] Task #1340 for pvparena v1.13.9.301 generated an exception
java.lang.ArrayIndexOutOfBoundsException: -1
	at net.slipcor.pvparena.arena.ArenaClass.equip(ArenaClass.java:166) ~[?:?]
	at net.slipcor.pvparena.runnables.InventoryRefillRunnable.run(InventoryRefillRunnable.java:88) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2_LATEST.jar:git-Spigot-573cdf2-dff66df]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot-1.13.2_LATEST.jar:git-Spigot-573cdf2-dff66df]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2_LATEST.jar:git-Spigot-573cdf2-dff66df]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2_LATEST.jar:git-Spigot-573cdf2-dff66df]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2_LATEST.jar:git-Spigot-573cdf2-dff66df]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2_LATEST.jar:git-Spigot-573cdf2-dff66df]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
`

https://i.gyazo.com/85b7bf64bfcc575725241278a0d91497.png

Spigot Version: 1.13.2
PA Version: v1.13.9.301

Let me know if there is anymore info you need.

Thanks!

Edit: The item does have NBT data if that helps. Uses ItemFlags  HIDE_ATTRIBUTES, HIDE_UNBREAKABLE, HIDE_POTION_EFFECTS
Config: https://pastebin.com/PFKAtM0m

**Comment by Eredrim** [comment]
Hello,
the refillInventory parameter requires you specify what you want to refill. In the "item" config block, you can use the "keepAllOnRespawn" property to true in order to keep all inventory. You can also set only items you want to keep with "keepOnRespawn" parameter.
From my part, I will patch the code to avoid the exception and write a message instead.

**Comment by TerraPrimal** [comment]
Thanks for the quick reply Eredrim,
Setting keepAllOnRespawn to true seems to have fixed the issue. Is there a difference between refillInventory and refillCustomInventory?
Although my items are being saved, it seems they're not being put back in the correct spot. For example, I have a book in the last slot of the hotbar, after being killed its moved to the next available slot.

I am more then happy to manage the players items returning after being killed using the PADeathEvent, if so what would be the best config options to just ignore it? All of them to false?

**Comment by Eredrim** [comment]
Hi,
refillCustomInventory allow refilling for a special class named "custom". It is really specific.
It is a normal stuff players items are not at the same place. On player death event, the plugin takes the items normally dropped by the player and put them in its inventory.
For your last question, I don't understand what you want. What do you want to ignore ?

**Comment by Oruss7** [comment]
ping @TerraPrimal

**Comment by Eredrim** [comment]
Issue close for no response
