### ISSUE TITLE
Goal Sabotage is broken

### ISSUE THREAD

**Issue by Oruss7** [Eredrim/pvparena#79]
- Ignite TNT does not make team lose/win.
- No protection againt teamate igniting there own tnt
- TNTs are note replaced after battle. (if we don't use blockrestore and WE of course)

**Comment by Eredrim** [comment]
```
[15:20:35] [Server thread/ERROR]: Could not pass event EntityExplodeEvent to pvparena v1.15.1
java.lang.NullPointerException: null
at net.slipcor.pvparena.goals.GoalSabotage.onTNTExplode(GoalSabotage.java:573) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor532.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-416]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-416]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-416]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.Explosion.a(Explosion.java:260) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.World.createExplosion(World.java:920) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.WorldServer.createExplosion(WorldServer.java:1605) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.World.createExplosion(World.java:913) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.EntityTNTPrimed.explode(EntityTNTPrimed.java:114) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.EntityTNTPrimed.tick(EntityTNTPrimed.java:73) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:845) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.World.a(World.java:887) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1355) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-416]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-416]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232] 
```
