### ISSUE TITLE
NullPointerException with MatchResultStats when arena is reloaded twice

### ISSUE THREAD

**Issue by Eredrim** [Eredrim/pvparena#96]
```
[23:58:42] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.15.2-SNAPSHOT-b6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:762) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1788) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1631) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1584) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NullPointerException
	at net.slipcor.pvparena.modules.matchresultstats.MatchResultStats.reset(MatchResultStats.java:176) ~[?:?]
	at net.slipcor.pvparena.loadables.ArenaModuleManager.reset(ArenaModuleManager.java:272) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.reset(Arena.java:1427) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.stop(Arena.java:1897) ~[?:?]
	at net.slipcor.pvparena.managers.ArenaManager.removeArena(ArenaManager.java:359) ~[?:?]
	at net.slipcor.pvparena.commands.PAA_Reload.commit(PAA_Reload.java:41) ~[?:?]
	at net.slipcor.pvparena.commands.PAA_ReloadAll.commit(PAA_ReloadAll.java:56) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:268) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.5.jar:3018-Spigot-db99f82-a021e33]
	... 19 more
```

**Comment by Eredrim** [comment]
Fixed
